package com.matez.wildnature.world.generation.structures.nature.woods.citrus;

import com.matez.wildnature.world.generation.structures.nature.SchemFeature;
import net.minecraft.util.math.BlockPos;

import java.util.Set;

public class peach3 extends SchemFeature {

    @Override
    public Set<BlockPos> setBlocks() {

        Block(0, 5, -4, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 4, -3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 5, -3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 5, -3, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 5, -3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 6, -3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 3, -2, "wildnature:citrus_branch[down=false,east=false,north=false,south=true,up=true,waterlogged=false,west=false]");
        Block(0, 3, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 4, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 4, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 4, -2, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 4, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 5, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 5, -2, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 5, -2, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 5, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(2, 5, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 6, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 6, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(1, 6, -2, "wildnature:citrus_branch[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=true]");
        Block(-1, 7, -2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 7, -2, "wildnature:citrus_branch[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=true]");
        Block(-2, 3, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 3, -1, "wildnature:citrus_branch[down=false,east=true,north=true,south=true,up=true,waterlogged=false,west=false]");
        Block(1, 3, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 4, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 4, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 4, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 4, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 4, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(2, 4, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(1, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(2, 5, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(3, 5, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 6, -1, "wildnature:citrus_branch[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=false]");
        Block(-1, 6, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 6, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 6, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(2, 6, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(3, 6, -1, "wildnature:citrus_branch[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=true]");
        Block(-2, 7, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 7, -1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 7, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 8, -1, "wildnature:citrus_branch[down=true,east=true,north=false,south=true,up=false,waterlogged=false,west=false]");
        Block(-1, 8, -1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 1, 0, "wildnature:citrus_log[axis=y]");
        Block(0, 2, 0, "wildnature:citrus_log[axis=y]");
        Block(-2, 3, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 3, 0, "wildnature:citrus_branch[down=false,east=true,north=false,south=false,up=true,waterlogged=false,west=true]");
        Block(0, 3, 0, "wildnature:citrus_log[axis=y]");
        Block(2, 3, 0, "wildnature:peach_leaves[distance=3,persistent=true,stage=0]");
        Block(-4, 4, 0, "wildnature:citrus_branch[down=false,east=true,north=false,south=false,up=true,waterlogged=false,west=false]");
        Block(-3, 4, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 4, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 4, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 4, 0, "wildnature:peach_leaves[distance=1,persistent=true,stage=0]");
        Block(1, 4, 0, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(2, 4, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(3, 4, 0, "wildnature:peach_leaves[distance=5,persistent=true,stage=0]");
        Block(-4, 5, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 5, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-2, 5, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 5, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(2, 5, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=false]");
        Block(3, 5, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(4, 5, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 6, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 6, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 6, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 6, 0, "wildnature:citrus_branch[down=false,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 6, 0, "wildnature:citrus_branch[down=false,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(2, 6, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(3, 6, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 7, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 7, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 7, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 7, 0, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 7, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 8, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 8, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 8, 0, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(1, 8, 0, "wildnature:citrus_branch[down=true,east=false,north=false,south=false,up=false,waterlogged=false,west=true]");
        Block(-1, 9, 0, "wildnature:citrus_branch[down=true,east=false,north=false,south=true,up=false,waterlogged=false,west=false]");
        Block(-2, 3, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 3, 1, "wildnature:citrus_log[axis=y]");
        Block(1, 3, 1, "wildnature:peach_leaves[distance=1,persistent=true,stage=0]");
        Block(2, 3, 1, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(-3, 4, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 4, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 4, 1, "wildnature:peach_leaves[distance=1,persistent=true,stage=0]");
        Block(0, 4, 1, "wildnature:citrus_log[axis=y]");
        Block(1, 4, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(2, 4, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(3, 4, 1, "wildnature:peach_leaves[distance=4,persistent=true,stage=0]");
        Block(-3, 5, 1, "wildnature:peach_leaves[distance=6,persistent=true,stage=0]");
        Block(-2, 5, 1, "wildnature:peach_leaves[distance=5,persistent=true,stage=0]");
        Block(0, 5, 1, "wildnature:citrus_log[axis=y]");
        Block(1, 5, 1, "wildnature:peach_leaves[distance=1,persistent=true,stage=0]");
        Block(2, 5, 1, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(3, 5, 1, "wildnature:peach_leaves[distance=3,persistent=true,stage=0]");
        Block(-3, 6, 1, "wildnature:citrus_branch[down=true,east=false,north=true,south=false,up=false,waterlogged=false,west=false]");
        Block(-1, 6, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(0, 6, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 6, 1, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(2, 6, 1, "wildnature:citrus_branch[down=true,east=false,north=true,south=false,up=false,waterlogged=false,west=true]");
        Block(-2, 7, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 7, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 7, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-3, 8, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 8, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 8, 1, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 8, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 9, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 9, 1, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(1, 3, 2, "wildnature:citrus_branch[down=false,east=false,north=true,south=false,up=true,waterlogged=false,west=false]");
        Block(-2, 4, 2, "wildnature:peach_leaves[distance=3,persistent=true,stage=0]");
        Block(-1, 4, 2, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(0, 4, 2, "wildnature:peach_leaves[distance=1,persistent=true,stage=0]");
        Block(1, 4, 2, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(2, 4, 2, "wildnature:peach_leaves[distance=3,persistent=true,stage=0]");
        Block(-2, 5, 2, "wildnature:peach_leaves[distance=4,persistent=true,stage=0]");
        Block(-1, 5, 2, "wildnature:citrus_branch[down=true,east=true,north=false,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 5, 2, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(1, 5, 2, "wildnature:peach_leaves[distance=2,persistent=true,stage=0]");
        Block(-2, 6, 2, "wildnature:peach_leaves[distance=5,persistent=true,stage=0]");
        Block(-1, 6, 2, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 6, 2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 7, 2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 8, 2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 8, 2, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 4, 3, "wildnature:peach_leaves[distance=4,persistent=true,stage=0]");
        Block(-1, 4, 3, "wildnature:peach_leaves[distance=3,persistent=true,stage=0]");
        Block(-3, 5, 3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 5, 3, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(-1, 5, 3, "wildnature:citrus_branch[down=true,east=true,north=true,south=true,up=true,waterlogged=false,west=true]");
        Block(0, 5, 3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-2, 6, 3, "wildnature:peach_leaves[distance=6,persistent=true,stage=0]");
        Block(-1, 6, 3, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 7, 3, "wildnature:citrus_branch[down=true,east=false,north=true,south=false,up=false,waterlogged=false,west=false]");
        Block(-2, 5, 4, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");
        Block(-1, 5, 4, "wildnature:peach_leaves[distance=7,persistent=true,stage=0]");

//   wildnature mod
//           created by matez 
//         all rights reserved   
//     https://wildnaturemod.com
        return super.setBlocks();
    }
}