package com.matez.wildnature.world.generation.structures.nature.fallen.baobab;

import com.matez.wildnature.world.generation.structures.nature.fallen.FallenSchemFeature;
import net.minecraft.util.math.BlockPos;

import java.util.Set;

public class fallen_big_baobab1 extends FallenSchemFeature {

    @Override
    public Set<BlockPos> setBlocks() {

        Block(-4, 1, -4, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(-3, 1, -4, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(0, 1, -4, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(1, 1, -4, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(-3, 2, -4, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(0, 2, -4, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(-5, 1, -3, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-4, 1, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-3, 1, -3, "wildnature:baobab_log[axis=z]");
        Block(-2, 1, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 1, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(0, 1, -3, "wildnature:baobab_log[axis=z]");
        Block(1, 1, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(2, 1, -3, "minecraft:vine[east=false,north=false,south=true,up=false,west=true]");
        Block(3, 1, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(4, 1, -3, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(-3, 2, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(0, 2, -3, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(3, 2, -3, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(-3, 1, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-2, 1, -2, "wildnature:baobab_log[axis=x]");
        Block(-1, 1, -2, "wildnature:baobab_log[axis=z]");
        Block(0, 1, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(1, 1, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(2, 1, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(3, 1, -2, "wildnature:baobab_log[axis=z]");
        Block(4, 1, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-3, 2, -2, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-2, 2, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 2, -2, "wildnature:baobab_log[axis=y]");
        Block(0, 2, -2, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(2, 2, -2, "minecraft:vine[east=true,north=false,south=true,up=false,west=false]");
        Block(3, 2, -2, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(4, 2, -2, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(-3, 1, -1, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-2, 1, -1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 1, -1, "wildnature:baobab_log[axis=z]");
        Block(0, 1, -1, "wildnature:baobab_log[axis=z]");
        Block(1, 1, -1, "wildnature:baobab_log[axis=x]");
        Block(2, 1, -1, "wildnature:baobab_log[axis=x]");
        Block(3, 1, -1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 2, -1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(0, 2, -1, "minecraft:vine[east=true,north=false,south=false,up=false,west=true]");
        Block(1, 2, -1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(2, 2, -1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-3, 1, 0, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-2, 1, 0, "wildnature:baobab_log[axis=x]");
        Block(-1, 1, 0, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 0, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 0, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(2, 1, 0, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(3, 1, 0, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(-3, 2, 0, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-2, 2, 0, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 2, 0, "wildnature:baobab_log[axis=z]");
        Block(2, 2, 0, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(-3, 1, 1, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-2, 1, 1, "wildnature:baobab_leaves[distance=1,persistent=true]");
        Block(-1, 1, 1, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 1, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 1, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(-2, 2, 1, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(-1, 2, 1, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 1, "wildnature:baobab_log[axis=z]");
        Block(-1, 1, 2, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 2, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 2, "wildnature:baobab_log[axis=z]");
        Block(1, 2, 2, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(0, 1, 3, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(1, 1, 3, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 3, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 4, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 4, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 4, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(0, 1, 5, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 5, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 5, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(0, 2, 5, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 6, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(1, 1, 6, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 6, "wildnature:baobab_log[axis=z]");
        Block(1, 2, 6, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 7, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 7, "minecraft:vine[east=false,north=false,south=true,up=false,west=true]");
        Block(1, 2, 7, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 8, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 8, "wildnature:baobab_log[axis=z]");
        Block(0, 2, 8, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(1, 2, 8, "wildnature:baobab_log[axis=z]");
        Block(0, 1, 9, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 9, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 9, "wildnature:baobab_log[axis=z]");
        Block(1, 2, 9, "wildnature:baobab_log[axis=z]");
        Block(2, 2, 9, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(0, 1, 10, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(1, 1, 10, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 10, "wildnature:baobab_log[axis=z]");
        Block(3, 1, 10, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(1, 2, 10, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 11, "wildnature:baobab_log[axis=z]");
        Block(1, 2, 11, "wildnature:baobab_log[axis=z]");
        Block(2, 2, 11, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 12, "wildnature:baobab_log[axis=z]");
        Block(2, 2, 12, "wildnature:baobab_log[axis=z]");
        Block(1, 1, 13, "wildnature:baobab_log[axis=z]");
        Block(2, 1, 13, "wildnature:baobab_log[axis=z]");
        Block(3, 1, 13, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(1, 0, 14, "wildnature:baobab_log[axis=y]");
        Block(2, 0, 14, "wildnature:baobab_log[axis=y]");
        Block(1, 1, 14, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(0, 0, 15, "wildnature:baobab_log[axis=y]");
        Block(1, 0, 15, "wildnature:baobab_log[axis=y]");
        Block(2, 0, 15, "wildnature:baobab_log[axis=y]");
        Block(3, 0, 15, "wildnature:baobab_log[axis=y]");
        Block(0, 1, 15, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(1, 1, 15, "wildnature:baobab_log[axis=y]");
        Block(2, 1, 15, "wildnature:baobab_log[axis=y]");
        Block(3, 1, 15, "minecraft:vine[east=false,north=false,south=true,up=false,west=false]");
        Block(2, 2, 15, "wildnature:baobab_log[axis=y]");
        Block(0, 0, 16, "wildnature:baobab_log[axis=y]");
        Block(1, 0, 16, "wildnature:baobab_log[axis=y]");
        Block(2, 0, 16, "wildnature:baobab_log[axis=y]");
        Block(3, 0, 16, "wildnature:baobab_log[axis=y]");
        Block(4, 0, 16, "wildnature:baobab_log[axis=y]");
        Block(1, 1, 16, "wildnature:baobab_log[axis=y]");
        Block(2, 1, 16, "wildnature:baobab_log[axis=y]");
        Block(3, 1, 16, "wildnature:baobab_log[axis=y]");
        Block(1, 2, 16, "wildnature:baobab_log[axis=y]");
        Block(2, 2, 16, "wildnature:baobab_log[axis=y]");
        Block(2, 3, 16, "wildnature:baobab_log[axis=y]");
        Block(3, 3, 16, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(0, 0, 17, "wildnature:baobab_log[axis=y]");
        Block(1, 0, 17, "wildnature:baobab_log[axis=y]");
        Block(2, 0, 17, "wildnature:baobab_log[axis=y]");
        Block(3, 0, 17, "wildnature:baobab_log[axis=y]");
        Block(0, 1, 17, "minecraft:vine[east=true,north=false,south=false,up=false,west=false]");
        Block(1, 1, 17, "wildnature:baobab_log[axis=y]");
        Block(2, 1, 17, "wildnature:baobab_log[axis=y]");
        Block(3, 1, 17, "minecraft:vine[east=false,north=false,south=false,up=false,west=true]");
        Block(1, 2, 17, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");
        Block(2, 2, 17, "wildnature:baobab_log[axis=y]");
        Block(2, 0, 18, "wildnature:baobab_log[axis=y]");
        Block(2, 2, 18, "minecraft:vine[east=false,north=true,south=false,up=false,west=false]");

//   wildnature mod
//           created by matez 
//         all rights reserved   
//     https://wildnaturemod.com
        return super.setBlocks();
    }
}