package com.matez.wildnature.common.registry.blocks;

import com.matez.wildnature.init.Main;
import com.matez.wildnature.common.blocks.*;
import com.matez.wildnature.client.tabs.WNTabs;
import com.matez.wildnature.util.lists.WNBlocks;
import net.minecraft.block.Block;
import net.minecraft.block.SoundType;
import net.minecraft.block.material.Material;
import net.minecraft.block.material.MaterialColor;
import net.minecraft.item.Item;

public class FurnitureRegistry {

    Block[] block;

    public FurnitureRegistry(){
        block = new Block[]{
                WNBlocks.OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("oak_bench")),
                WNBlocks.SPRUCE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("spruce_bench")),
                WNBlocks.BIRCH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("birch_bench")),
                WNBlocks.JUNGLE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jungle_bench")),
                WNBlocks.ACACIA_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("acacia_bench")),
                WNBlocks.DARK_OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("dark_oak_bench")),
                WNBlocks.ROSACEAE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("rosaceae_bench")),
                WNBlocks.BAOBAB_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("baobab_bench")),
                WNBlocks.BEECH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("beech_bench")),
                WNBlocks.CEDAR_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cedar_bench")),
                WNBlocks.CHERRY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cherry_bench")),
                WNBlocks.CITRUS_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("citrus_bench")),
                WNBlocks.EBONY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("ebony_bench")),
                WNBlocks.EUCALYPTUS_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("eucalyptus_bench")),
                WNBlocks.JACARANDA_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jacaranda_bench")),
                WNBlocks.LARCH_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("larch_bench")),
                WNBlocks.MAHOGANY_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mahogany_bench")),
                WNBlocks.MANGROVE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mangrove_bench")),
                WNBlocks.MAPLE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("maple_bench")),
                WNBlocks.PALM_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("palm_bench")),
                WNBlocks.PINE_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("pine_bench")),
                WNBlocks.PLUM_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("plum_bench")),
                WNBlocks.REDWOOD_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("redwood_bench")),
                WNBlocks.WILLOW_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("willow_bench")),
                WNBlocks.GLOWING_CAVE_OAK_BENCH = new BasicBench(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowing_cave_oak_bench")),

                WNBlocks.OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("oak_chair")),
                WNBlocks.SPRUCE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("spruce_chair")),
                WNBlocks.BIRCH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("birch_chair")),
                WNBlocks.JUNGLE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jungle_chair")),
                WNBlocks.ACACIA_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("acacia_chair")),
                WNBlocks.DARK_OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("dark_oak_chair")),
                WNBlocks.ROSACEAE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("rosaceae_chair")),
                WNBlocks.BAOBAB_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("baobab_chair")),
                WNBlocks.BEECH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("beech_chair")),
                WNBlocks.CEDAR_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cedar_chair")),
                WNBlocks.CHERRY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cherry_chair")),
                WNBlocks.CITRUS_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("citrus_chair")),
                WNBlocks.EBONY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("ebony_chair")),
                WNBlocks.EUCALYPTUS_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("eucalyptus_chair")),
                WNBlocks.JACARANDA_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jacaranda_chair")),
                WNBlocks.LARCH_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("larch_chair")),
                WNBlocks.MAHOGANY_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mahogany_chair")),
                WNBlocks.MANGROVE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mangrove_chair")),
                WNBlocks.MAPLE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("maple_chair")),
                WNBlocks.PALM_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("palm_chair")),
                WNBlocks.PINE_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("pine_chair")),
                WNBlocks.PLUM_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("plum_chair")),
                WNBlocks.REDWOOD_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("redwood_chair")),
                WNBlocks.WILLOW_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("willow_chair")),
                WNBlocks.GLOWING_CAVE_OAK_CHAIR = new BasicChair(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowing_cave_oak_chair")),

                WNBlocks.OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("oak_round_table")),
                WNBlocks.SPRUCE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("spruce_round_table")),
                WNBlocks.BIRCH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("birch_round_table")),
                WNBlocks.JUNGLE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jungle_round_table")),
                WNBlocks.ACACIA_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("acacia_round_table")),
                WNBlocks.DARK_OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("dark_oak_round_table")),
                WNBlocks.ROSACEAE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("rosaceae_round_table")),
                WNBlocks.BAOBAB_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("baobab_round_table")),
                WNBlocks.BEECH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("beech_round_table")),
                WNBlocks.CEDAR_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cedar_round_table")),
                WNBlocks.CHERRY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cherry_round_table")),
                WNBlocks.CITRUS_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("citrus_round_table")),
                WNBlocks.EBONY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("ebony_round_table")),
                WNBlocks.EUCALYPTUS_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("eucalyptus_round_table")),
                WNBlocks.JACARANDA_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jacaranda_round_table")),
                WNBlocks.LARCH_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("larch_round_table")),
                WNBlocks.MAHOGANY_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mahogany_round_table")),
                WNBlocks.MANGROVE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mangrove_round_table")),
                WNBlocks.MAPLE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("maple_round_table")),
                WNBlocks.PALM_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("palm_round_table")),
                WNBlocks.PINE_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("pine_round_table")),
                WNBlocks.PLUM_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("plum_round_table")),
                WNBlocks.REDWOOD_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("redwood_round_table")),
                WNBlocks.WILLOW_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("willow_round_table")),
                WNBlocks.GLOWING_CAVE_OAK_ROUND_TABLE = new BasicRoundTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowing_cave_oak_round_table")),

                WNBlocks.OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("oak_square_table")),
                WNBlocks.SPRUCE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("spruce_square_table")),
                WNBlocks.BIRCH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("birch_square_table")),
                WNBlocks.JUNGLE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jungle_square_table")),
                WNBlocks.ACACIA_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("acacia_square_table")),
                WNBlocks.DARK_OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("dark_oak_square_table")),
                WNBlocks.ROSACEAE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("rosaceae_square_table")),
                WNBlocks.BAOBAB_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("baobab_square_table")),
                WNBlocks.BEECH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("beech_square_table")),
                WNBlocks.CEDAR_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cedar_square_table")),
                WNBlocks.CHERRY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cherry_square_table")),
                WNBlocks.CITRUS_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("citrus_square_table")),
                WNBlocks.EBONY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("ebony_square_table")),
                WNBlocks.EUCALYPTUS_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("eucalyptus_square_table")),
                WNBlocks.JACARANDA_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jacaranda_square_table")),
                WNBlocks.LARCH_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("larch_square_table")),
                WNBlocks.MAHOGANY_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mahogany_square_table")),
                WNBlocks.MANGROVE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mangrove_square_table")),
                WNBlocks.MAPLE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("maple_square_table")),
                WNBlocks.PALM_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("palm_square_table")),
                WNBlocks.PINE_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("pine_square_table")),
                WNBlocks.PLUM_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("plum_square_table")),
                WNBlocks.REDWOOD_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("redwood_square_table")),
                WNBlocks.WILLOW_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("willow_square_table")),
                WNBlocks.GLOWING_CAVE_OAK_SQUARE_TABLE = new BasicSquareTable(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowing_cave_oak_square_table")),

                WNBlocks.OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("oak_stool")),
                WNBlocks.SPRUCE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("spruce_stool")),
                WNBlocks.BIRCH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("birch_stool")),
                WNBlocks.JUNGLE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jungle_stool")),
                WNBlocks.ACACIA_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("acacia_stool")),
                WNBlocks.DARK_OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("dark_oak_stool")),
                WNBlocks.ROSACEAE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("rosaceae_stool")),
                WNBlocks.BAOBAB_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("baobab_stool")),
                WNBlocks.BEECH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("beech_stool")),
                WNBlocks.CEDAR_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cedar_stool")),
                WNBlocks.CHERRY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("cherry_stool")),
                WNBlocks.CITRUS_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("citrus_stool")),
                WNBlocks.EBONY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("ebony_stool")),
                WNBlocks.EUCALYPTUS_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("eucalyptus_stool")),
                WNBlocks.JACARANDA_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("jacaranda_stool")),
                WNBlocks.LARCH_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("larch_stool")),
                WNBlocks.MAHOGANY_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mahogany_stool")),
                WNBlocks.MANGROVE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mangrove_stool")),
                WNBlocks.MAPLE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("maple_stool")),
                WNBlocks.PALM_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("palm_stool")),
                WNBlocks.PINE_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("pine_stool")),
                WNBlocks.PLUM_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("plum_stool")),
                WNBlocks.REDWOOD_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("redwood_stool")),
                WNBlocks.WILLOW_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("willow_stool")),
                WNBlocks.GLOWING_CAVE_OAK_STOOL = new BasicStool(Block.Properties.create(Material.WOOD).sound(SoundType.WOOD).hardnessAndResistance(1.5F, 0.8F), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowing_cave_oak_stool")),


                WNBlocks.UNTIED_STRAWBALE = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("untied_strawbale")),
                WNBlocks.UNTIED_STRAWBALE_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("untied_strawbale_slab")),
                WNBlocks.UNTIED_STRAWBALE_STAIRS = new StairsBase(WNBlocks.UNTIED_STRAWBALE.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("untied_strawbale_stairs")),

                WNBlocks.STRAWBALE = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale")),
                WNBlocks.STRAWBALE_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_slab")),
                WNBlocks.STRAWBALE_STAIRS = new StairsBase(WNBlocks.STRAWBALE.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_stairs")),

                WNBlocks.STRAWBALE_AGED = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged")),
                WNBlocks.STRAWBALE_AGED_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged_slab")),
                WNBlocks.STRAWBALE_AGED_STAIRS = new StairsBase(WNBlocks.STRAWBALE_AGED.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged_stairs")),

                WNBlocks.STRAWBALE_AGED_BROWN = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged_brown")),
                WNBlocks.STRAWBALE_AGED_BROWN_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged_brown_slab")),
                WNBlocks.STRAWBALE_AGED_BROWN_STAIRS = new StairsBase(WNBlocks.STRAWBALE_AGED_BROWN.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_aged_brown_stairs")),

                WNBlocks.STRAWBALE_OLD = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old")),
                WNBlocks.STRAWBALE_OLD_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old_slab")),
                WNBlocks.STRAWBALE_OLD_STAIRS = new StairsBase(WNBlocks.STRAWBALE_OLD.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old_stairs")),

                WNBlocks.STRAWBALE_OLD_BROWN = new BlockBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old_brown")),
                WNBlocks.STRAWBALE_OLD_BROWN_SLAB = new SlabBase(Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old_brown_slab")),
                WNBlocks.STRAWBALE_OLD_BROWN_STAIRS = new StairsBase(WNBlocks.STRAWBALE_OLD_BROWN.getDefaultState(),Block.Properties.create(Material.ORGANIC, MaterialColor.YELLOW).hardnessAndResistance(0.5F).sound(SoundType.PLANT), new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("strawbale_old_brown_stairs")),

                WNBlocks.BONES_BLOCK = new BlockBase(Block.Properties.create(Material.ROCK).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("bones_block")),

                WNBlocks.STONE_LAMP = new LampBase(Block.Properties.create(Material.ROCK).lightValue(15).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("stone_lamp")),
                WNBlocks.MOSSY_STONE_LAMP = new LampBase(Block.Properties.create(Material.ROCK).lightValue(15).hardnessAndResistance(1.3F).sound(SoundType.STONE),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("mossy_stone_lamp")),
                WNBlocks.VILLAGE_LAMP = new LampBase(Block.Properties.create(Material.MISCELLANEOUS).lightValue(15).hardnessAndResistance(0.3F).sound(SoundType.GLASS),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("village_lamp")),

                WNBlocks.CANDLE = new CandleBase(Block.Properties.create(Material.MISCELLANEOUS).hardnessAndResistance(0.4F,0.2F).sound(SoundType.STONE).lightValue(10),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("candle")),
                WNBlocks.LIGHTNING_BUG = new LightningBugBlock(Block.Properties.create(Material.ORGANIC).hardnessAndResistance(0.1F,0F).doesNotBlockMovement().sound(SoundType.SWEET_BERRY_BUSH).lightValue(5),new Item.Properties().group(WNTabs.SURFACE), Main.RegistryEvents.location("lightning_bug")),
                WNBlocks.GLOWSHROOM_LANTERN = new ShroomLantern(Block.Properties.create(Material.IRON).hardnessAndResistance(3.5F).sound(SoundType.LANTERN).lightValue(10),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("glowshroom_lantern")),
                WNBlocks.ICESHROOM_LANTERN = new ShroomLantern(Block.Properties.create(Material.IRON).hardnessAndResistance(3.5F).sound(SoundType.LANTERN).lightValue(10),new Item.Properties().group(WNTabs.FURNITURE), Main.RegistryEvents.location("iceshroom_lantern")),

        };
    }

    public Block[] getBlock() {
        return block;
    }
}
