package net.matez.pokeUniverseBiomeBuilder;

import java.util.ArrayList;

public class Structures {
    public ArrayList<String> structures = new ArrayList<>();
    public Structures(){
//folder: cactus
addStructureID("cactus/cactus_1");
addStructureID("cactus/cactus_10");
addStructureID("cactus/cactus_11");
addStructureID("cactus/cactus_2");
addStructureID("cactus/cactus_3");
addStructureID("cactus/cactus_4");
addStructureID("cactus/cactus_5");
addStructureID("cactus/cactus_6");
addStructureID("cactus/cactus_7");
addStructureID("cactus/cactus_8");
addStructureID("cactus/cactus_9");
//folder: coral\yellow
addStructureID("coral/yellow/coral_yellow_1");
addStructureID("coral/yellow/coral_yellow_10");
addStructureID("coral/yellow/coral_yellow_11");
addStructureID("coral/yellow/coral_yellow_12");
addStructureID("coral/yellow/coral_yellow_13");
addStructureID("coral/yellow/coral_yellow_14");
addStructureID("coral/yellow/coral_yellow_15");
addStructureID("coral/yellow/coral_yellow_16");
addStructureID("coral/yellow/coral_yellow_17");
addStructureID("coral/yellow/coral_yellow_18");
addStructureID("coral/yellow/coral_yellow_19");
addStructureID("coral/yellow/coral_yellow_2");
addStructureID("coral/yellow/coral_yellow_20");
addStructureID("coral/yellow/coral_yellow_3");
addStructureID("coral/yellow/coral_yellow_4");
addStructureID("coral/yellow/coral_yellow_5");
addStructureID("coral/yellow/coral_yellow_6");
addStructureID("coral/yellow/coral_yellow_7");
addStructureID("coral/yellow/coral_yellow_8");
addStructureID("coral/yellow/coral_yellow_9");
//folder: flower\big
addStructureID("flower/big/big_flower");
addStructureID("flower/big/big_flower_2");
addStructureID("flower/big/big_flower_3");
addStructureID("flower/big/big_flower_4");
addStructureID("flower/big/big_flower_5");
addStructureID("flower/big/big_flower_6");
//folder: flower\normal
addStructureID("flower/normal/flower_1");
addStructureID("flower/normal/flower_10");
addStructureID("flower/normal/flower_11");
addStructureID("flower/normal/flower_12");
addStructureID("flower/normal/flower_13");
addStructureID("flower/normal/flower_14");
addStructureID("flower/normal/flower_15");
addStructureID("flower/normal/flower_16");
addStructureID("flower/normal/flower_17");
addStructureID("flower/normal/flower_18");
addStructureID("flower/normal/flower_19");
addStructureID("flower/normal/flower_2");
addStructureID("flower/normal/flower_20");
addStructureID("flower/normal/flower_21");
addStructureID("flower/normal/flower_22");
addStructureID("flower/normal/flower_23");
addStructureID("flower/normal/flower_24");
addStructureID("flower/normal/flower_25");
addStructureID("flower/normal/flower_26");
addStructureID("flower/normal/flower_3");
addStructureID("flower/normal/flower_4");
addStructureID("flower/normal/flower_5");
addStructureID("flower/normal/flower_6");
addStructureID("flower/normal/flower_7");
addStructureID("flower/normal/flower_8");
addStructureID("flower/normal/flower_9");
//folder: icicle\big
addStructureID("icicle/big/icicle_big_1");
addStructureID("icicle/big/icicle_big_2");
//folder: icicle\connected
addStructureID("icicle/connected/icicle_connected_1");
addStructureID("icicle/connected/icicle_connected_2");
//folder: icicle\four
addStructureID("icicle/four/icicle_four_1");
//folder: icicle\normal
addStructureID("icicle/normal/icicle_normal_1");
addStructureID("icicle/normal/icicle_normal_10");
addStructureID("icicle/normal/icicle_normal_11");
addStructureID("icicle/normal/icicle_normal_12");
addStructureID("icicle/normal/icicle_normal_13");
addStructureID("icicle/normal/icicle_normal_14");
addStructureID("icicle/normal/icicle_normal_15");
addStructureID("icicle/normal/icicle_normal_2");
addStructureID("icicle/normal/icicle_normal_3");
addStructureID("icicle/normal/icicle_normal_4");
addStructureID("icicle/normal/icicle_normal_5");
addStructureID("icicle/normal/icicle_normal_6");
addStructureID("icicle/normal/icicle_normal_7");
addStructureID("icicle/normal/icicle_normal_8");
addStructureID("icicle/normal/icicle_normal_9");
//folder: mountains\dungeon
addStructureID("mountains/dungeon/dungeon_mountain_1");
addStructureID("mountains/dungeon/dungeon_mountain_2");
//folder: mountains\mining
addStructureID("mountains/mining/mining_mountain_1");
//folder: mushroom\brown
addStructureID("mushroom/brown/mushroom_brown_1");
addStructureID("mushroom/brown/mushroom_brown_10");
addStructureID("mushroom/brown/mushroom_brown_11");
addStructureID("mushroom/brown/mushroom_brown_12");
addStructureID("mushroom/brown/mushroom_brown_13");
addStructureID("mushroom/brown/mushroom_brown_14");
addStructureID("mushroom/brown/mushroom_brown_15");
addStructureID("mushroom/brown/mushroom_brown_2");
addStructureID("mushroom/brown/mushroom_brown_3");
addStructureID("mushroom/brown/mushroom_brown_4");
addStructureID("mushroom/brown/mushroom_brown_5");
addStructureID("mushroom/brown/mushroom_brown_6");
addStructureID("mushroom/brown/mushroom_brown_7");
addStructureID("mushroom/brown/mushroom_brown_8");
addStructureID("mushroom/brown/mushroom_brown_9");
//folder: mushroom\brown-white
addStructureID("mushroom/brown-white/mushroom_brown_white_1");
addStructureID("mushroom/brown-white/mushroom_brown_white_2");
addStructureID("mushroom/brown-white/mushroom_brown_white_3");
addStructureID("mushroom/brown-white/mushroom_brown_white_4");
addStructureID("mushroom/brown-white/mushroom_brown_white_5");
addStructureID("mushroom/brown-white/mushroom_brown_white_6");
addStructureID("mushroom/brown-white/mushroom_brown_white_7");
addStructureID("mushroom/brown-white/mushroom_brown_white_8");
addStructureID("mushroom/brown-white/mushroom_brown_white_9");
//folder: mushroom\red\medium
addStructureID("mushroom/red/medium/mushroom_red_medium4");
addStructureID("mushroom/red/medium/mushroom_red_medium_1");
addStructureID("mushroom/red/medium/mushroom_red_medium_2");
addStructureID("mushroom/red/medium/mushroom_red_medium_3");
addStructureID("mushroom/red/medium/mushroom_red_medium_4");
addStructureID("mushroom/red/medium/mushroom_red_medium_5");
addStructureID("mushroom/red/medium/mushroom_red_medium_6");
addStructureID("mushroom/red/medium/mushroom_red_medium_7");
//folder: mushroom\red\normal
addStructureID("mushroom/red/normal/mushroom_red_1");
addStructureID("mushroom/red/normal/mushroom_red_10");
addStructureID("mushroom/red/normal/mushroom_red_11");
addStructureID("mushroom/red/normal/mushroom_red_12");
addStructureID("mushroom/red/normal/mushroom_red_2");
addStructureID("mushroom/red/normal/mushroom_red_3");
addStructureID("mushroom/red/normal/mushroom_red_4");
addStructureID("mushroom/red/normal/mushroom_red_5");
addStructureID("mushroom/red/normal/mushroom_red_6");
addStructureID("mushroom/red/normal/mushroom_red_7");
addStructureID("mushroom/red/normal/mushroom_red_8");
addStructureID("mushroom/red/normal/mushroom_red_9");
//folder: mushroom\white
addStructureID("mushroom/white/mushroom_white_1");
addStructureID("mushroom/white/mushroom_white_2");
addStructureID("mushroom/white/mushroom_white_3");
addStructureID("mushroom/white/mushroom_white_4");
addStructureID("mushroom/white/mushroom_white_5");
addStructureID("mushroom/white/mushroom_white_6");
addStructureID("mushroom/white/mushroom_white_7");
//folder: mushroom\yellow
addStructureID("mushroom/yellow/mushroom_yellow_1");
addStructureID("mushroom/yellow/mushroom_yellow_2");
addStructureID("mushroom/yellow/mushroom_yellow_3");
addStructureID("mushroom/yellow/mushroom_yellow_4");
addStructureID("mushroom/yellow/mushroom_yellow_5");
addStructureID("mushroom/yellow/mushroom_yellow_6");
addStructureID("mushroom/yellow/mushroom_yellow_7");
addStructureID("mushroom/yellow/mushroom_yellow_8");
addStructureID("mushroom/yellow/mushroom_yellow_9");
//folder: pumpkin\normal
addStructureID("pumpkin/normal/pumpkin_1");
addStructureID("pumpkin/normal/pumpkin_2");
addStructureID("pumpkin/normal/pumpkin_3");
addStructureID("pumpkin/normal/pumpkin_4");
addStructureID("pumpkin/normal/pumpkin_5");
addStructureID("pumpkin/normal/pumpkin_6");
addStructureID("pumpkin/normal/pumpkin_7");
addStructureID("pumpkin/normal/pumpkin_8");
//folder: pumpkin\pumpkins
addStructureID("pumpkin/pumpkins/pumpkins");
//folder: rocks\mini
addStructureID("rocks/mini/rock_mini_1");
addStructureID("rocks/mini/rock_mini_10");
addStructureID("rocks/mini/rock_mini_11");
addStructureID("rocks/mini/rock_mini_12");
addStructureID("rocks/mini/rock_mini_13");
addStructureID("rocks/mini/rock_mini_14");
addStructureID("rocks/mini/rock_mini_15");
addStructureID("rocks/mini/rock_mini_16");
addStructureID("rocks/mini/rock_mini_17");
addStructureID("rocks/mini/rock_mini_18");
addStructureID("rocks/mini/rock_mini_19");
addStructureID("rocks/mini/rock_mini_2");
addStructureID("rocks/mini/rock_mini_20");
addStructureID("rocks/mini/rock_mini_3");
addStructureID("rocks/mini/rock_mini_4");
addStructureID("rocks/mini/rock_mini_5");
addStructureID("rocks/mini/rock_mini_56");
addStructureID("rocks/mini/rock_mini_6");
addStructureID("rocks/mini/rock_mini_7");
addStructureID("rocks/mini/rock_mini_8");
addStructureID("rocks/mini/rock_mini_9");
//folder: rocks\normal
addStructureID("rocks/normal/rock_1");
addStructureID("rocks/normal/rock_10");
addStructureID("rocks/normal/rock_11");
addStructureID("rocks/normal/rock_12");
addStructureID("rocks/normal/rock_13");
addStructureID("rocks/normal/rock_14");
addStructureID("rocks/normal/rock_15");
addStructureID("rocks/normal/rock_16");
addStructureID("rocks/normal/rock_17");
addStructureID("rocks/normal/rock_18");
addStructureID("rocks/normal/rock_19");
addStructureID("rocks/normal/rock_2");
addStructureID("rocks/normal/rock_20");
addStructureID("rocks/normal/rock_21");
addStructureID("rocks/normal/rock_22");
addStructureID("rocks/normal/rock_23");
addStructureID("rocks/normal/rock_24");
addStructureID("rocks/normal/rock_25");
addStructureID("rocks/normal/rock_26");
addStructureID("rocks/normal/rock_27");
addStructureID("rocks/normal/rock_28");
addStructureID("rocks/normal/rock_29");
addStructureID("rocks/normal/rock_3");
addStructureID("rocks/normal/rock_30");
addStructureID("rocks/normal/rock_31");
addStructureID("rocks/normal/rock_32");
addStructureID("rocks/normal/rock_33");
addStructureID("rocks/normal/rock_34");
addStructureID("rocks/normal/rock_35");
addStructureID("rocks/normal/rock_36");
addStructureID("rocks/normal/rock_37");
addStructureID("rocks/normal/rock_38");
addStructureID("rocks/normal/rock_39");
addStructureID("rocks/normal/rock_4");
addStructureID("rocks/normal/rock_40");
addStructureID("rocks/normal/rock_41");
addStructureID("rocks/normal/rock_42");
addStructureID("rocks/normal/rock_43");
addStructureID("rocks/normal/rock_44");
addStructureID("rocks/normal/rock_45");
addStructureID("rocks/normal/rock_46");
addStructureID("rocks/normal/rock_47");
addStructureID("rocks/normal/rock_48");
addStructureID("rocks/normal/rock_49");
addStructureID("rocks/normal/rock_5");
addStructureID("rocks/normal/rock_50");
addStructureID("rocks/normal/rock_50_");
addStructureID("rocks/normal/rock_51");
addStructureID("rocks/normal/rock_52");
addStructureID("rocks/normal/rock_53");
addStructureID("rocks/normal/rock_54");
addStructureID("rocks/normal/rock_55");
addStructureID("rocks/normal/rock_56");
addStructureID("rocks/normal/rock_57");
addStructureID("rocks/normal/rock_58");
addStructureID("rocks/normal/rock_6");
addStructureID("rocks/normal/rock_7");
addStructureID("rocks/normal/rock_8");
addStructureID("rocks/normal/rock_9");
//folder: shrubs\cobble
addStructureID("shrubs/cobble/shrub_cobble_1");
addStructureID("shrubs/cobble/shrub_cobble_10");
addStructureID("shrubs/cobble/shrub_cobble_11");
addStructureID("shrubs/cobble/shrub_cobble_12");
addStructureID("shrubs/cobble/shrub_cobble_13");
addStructureID("shrubs/cobble/shrub_cobble_14");
addStructureID("shrubs/cobble/shrub_cobble_15");
addStructureID("shrubs/cobble/shrub_cobble_16");
addStructureID("shrubs/cobble/shrub_cobble_17");
addStructureID("shrubs/cobble/shrub_cobble_2");
addStructureID("shrubs/cobble/shrub_cobble_3");
addStructureID("shrubs/cobble/shrub_cobble_5");
addStructureID("shrubs/cobble/shrub_cobble_6");
addStructureID("shrubs/cobble/shrub_cobble_7");
addStructureID("shrubs/cobble/shrub_cobble_8");
addStructureID("shrubs/cobble/shrub_cobble_9");
//folder: shrubs\jungle
addStructureID("shrubs/jungle/shrub_jungle_1");
addStructureID("shrubs/jungle/shrub_jungle_10");
addStructureID("shrubs/jungle/shrub_jungle_11");
addStructureID("shrubs/jungle/shrub_jungle_12");
addStructureID("shrubs/jungle/shrub_jungle_13");
addStructureID("shrubs/jungle/shrub_jungle_14");
addStructureID("shrubs/jungle/shrub_jungle_15");
addStructureID("shrubs/jungle/shrub_jungle_16");
addStructureID("shrubs/jungle/shrub_jungle_17");
addStructureID("shrubs/jungle/shrub_jungle_18");
addStructureID("shrubs/jungle/shrub_jungle_19");
addStructureID("shrubs/jungle/shrub_jungle_2");
addStructureID("shrubs/jungle/shrub_jungle_20");
addStructureID("shrubs/jungle/shrub_jungle_21");
addStructureID("shrubs/jungle/shrub_jungle_22");
addStructureID("shrubs/jungle/shrub_jungle_23");
addStructureID("shrubs/jungle/shrub_jungle_3");
addStructureID("shrubs/jungle/shrub_jungle_4");
addStructureID("shrubs/jungle/shrub_jungle_5");
addStructureID("shrubs/jungle/shrub_jungle_6");
addStructureID("shrubs/jungle/shrub_jungle_7");
addStructureID("shrubs/jungle/shrub_jungle_8");
addStructureID("shrubs/jungle/shrub_jungle_9");
//folder: shrubs\oak
addStructureID("shrubs/oak/shrub_oak_1");
addStructureID("shrubs/oak/shrub_oak_10");
addStructureID("shrubs/oak/shrub_oak_11");
addStructureID("shrubs/oak/shrub_oak_12");
addStructureID("shrubs/oak/shrub_oak_13");
addStructureID("shrubs/oak/shrub_oak_14");
addStructureID("shrubs/oak/shrub_oak_15");
addStructureID("shrubs/oak/shrub_oak_16");
addStructureID("shrubs/oak/shrub_oak_17");
addStructureID("shrubs/oak/shrub_oak_18");
addStructureID("shrubs/oak/shrub_oak_19");
addStructureID("shrubs/oak/shrub_oak_2");
addStructureID("shrubs/oak/shrub_oak_20");
addStructureID("shrubs/oak/shrub_oak_21");
addStructureID("shrubs/oak/shrub_oak_22");
addStructureID("shrubs/oak/shrub_oak_23");
addStructureID("shrubs/oak/shrub_oak_24");
addStructureID("shrubs/oak/shrub_oak_25");
addStructureID("shrubs/oak/shrub_oak_26");
addStructureID("shrubs/oak/shrub_oak_27");
addStructureID("shrubs/oak/shrub_oak_28");
addStructureID("shrubs/oak/shrub_oak_29");
addStructureID("shrubs/oak/shrub_oak_3");
addStructureID("shrubs/oak/shrub_oak_30");
addStructureID("shrubs/oak/shrub_oak_31");
addStructureID("shrubs/oak/shrub_oak_32");
addStructureID("shrubs/oak/shrub_oak_33");
addStructureID("shrubs/oak/shrub_oak_34");
addStructureID("shrubs/oak/shrub_oak_35");
addStructureID("shrubs/oak/shrub_oak_36");
addStructureID("shrubs/oak/shrub_oak_4");
addStructureID("shrubs/oak/shrub_oak_5");
addStructureID("shrubs/oak/shrub_oak_6");
addStructureID("shrubs/oak/shrub_oak_7");
addStructureID("shrubs/oak/shrub_oak_8");
addStructureID("shrubs/oak/shrub_oak_9");
//folder: shrubs\psychic
addStructureID("shrubs/psychic/psychic_shrub_1");
addStructureID("shrubs/psychic/psychic_shrub_10");
addStructureID("shrubs/psychic/psychic_shrub_11");
addStructureID("shrubs/psychic/psychic_shrub_12");
addStructureID("shrubs/psychic/psychic_shrub_123_");
addStructureID("shrubs/psychic/psychic_shrub_13");
addStructureID("shrubs/psychic/psychic_shrub_14");
addStructureID("shrubs/psychic/psychic_shrub_15");
addStructureID("shrubs/psychic/psychic_shrub_16");
addStructureID("shrubs/psychic/psychic_shrub_17");
addStructureID("shrubs/psychic/psychic_shrub_178");
addStructureID("shrubs/psychic/psychic_shrub_18");
addStructureID("shrubs/psychic/psychic_shrub_19");
addStructureID("shrubs/psychic/psychic_shrub_2");
addStructureID("shrubs/psychic/psychic_shrub_20");
addStructureID("shrubs/psychic/psychic_shrub_21");
addStructureID("shrubs/psychic/psychic_shrub_212");
addStructureID("shrubs/psychic/psychic_shrub_22");
addStructureID("shrubs/psychic/psychic_shrub_23");
addStructureID("shrubs/psychic/psychic_shrub_24");
addStructureID("shrubs/psychic/psychic_shrub_25");
addStructureID("shrubs/psychic/psychic_shrub_26");
addStructureID("shrubs/psychic/psychic_shrub_3");
addStructureID("shrubs/psychic/psychic_shrub_4");
addStructureID("shrubs/psychic/psychic_shrub_5");
addStructureID("shrubs/psychic/psychic_shrub_6");
addStructureID("shrubs/psychic/psychic_shrub_7");
addStructureID("shrubs/psychic/psychic_shrub_8");
addStructureID("shrubs/psychic/psychic_shrub_9");
//folder: structures\battlegrounds\ice
addStructureID("structures/battlegrounds/ice/icebattle_1");
//folder: structures\battlegrounds\podzoldirt
addStructureID("structures/battlegrounds/podzoldirt/podzoldirtbattle_1");
//folder: structures\battlegrounds\sand
addStructureID("structures/battlegrounds/sand/sandbattle_1");
//folder: structures\bones
addStructureID("structures/bones/bones");
//folder: structures\campfire
addStructureID("structures/campfire/campfire_1");
addStructureID("structures/campfire/campfire_2");
//folder: structures\cavehouse
addStructureID("structures/cavehouse/cave_house_1");
//folder: structures\crater
addStructureID("structures/crater/crater_1");
//folder: structures\dumpster
addStructureID("structures/dumpster/dumpster_1");
//folder: structures\egg
addStructureID("structures/egg/egg_1");
addStructureID("structures/egg/egg_2");
addStructureID("structures/egg/egg_3");
addStructureID("structures/egg/egg_4");
addStructureID("structures/egg/egg_5");
addStructureID("structures/egg/egg_6");
//folder: structures\flying\house
addStructureID("structures/flying/house/flying_house_1");
//folder: structures\flying\tree
addStructureID("structures/flying/tree/flying_tree_1");
addStructureID("structures/flying/tree/flying_tree_2");
//folder: structures\house
addStructureID("structures/house/house_1");
addStructureID("structures/house/house_2");
addStructureID("structures/house/house_3");
//folder: structures\lab
addStructureID("structures/lab/lab_1");
//folder: structures\pokecenter
addStructureID("structures/pokecenter/pokecenter_1");
addStructureID("structures/pokecenter/pokecenter_broken_1");
//folder: structures\pokemarket
addStructureID("structures/pokemarket/pokemarket_1");
//folder: structures\pokemonpoop
addStructureID("structures/pokemonpoop/poop_1");
//folder: structures\psychiclegendary
addStructureID("structures/psychiclegendary/psychic_spawner");
//folder: structures\sandisland
addStructureID("structures/sandisland/sandisland_little_pool_1");
//folder: structures\skull
addStructureID("structures/skull/skull");
//folder: structures\slime
addStructureID("structures/slime/slime_1");
//folder: structures\statue
addStructureID("structures/statue/forest_statue");
addStructureID("structures/statue/ice_statue");
//folder: structures\train
addStructureID("structures/train/train_1");
//folder: swamp water structure
addStructureID("swamp water structure/swamp_water_structure_1");
addStructureID("swamp water structure/swamp_water_structure_10");
addStructureID("swamp water structure/swamp_water_structure_11");
addStructureID("swamp water structure/swamp_water_structure_12");
addStructureID("swamp water structure/swamp_water_structure_2");
addStructureID("swamp water structure/swamp_water_structure_3");
addStructureID("swamp water structure/swamp_water_structure_4");
addStructureID("swamp water structure/swamp_water_structure_5");
addStructureID("swamp water structure/swamp_water_structure_6");
addStructureID("swamp water structure/swamp_water_structure_7");
addStructureID("swamp water structure/swamp_water_structure_8");
addStructureID("swamp water structure/swamp_water_structure_9");
//folder: trees\big_insane_tree
addStructureID("trees/big_insane_tree/big_insane_tree");
//folder: trees\birch_trees\mini
addStructureID("trees/birch_trees/mini/birch_mini_tree_1");
addStructureID("trees/birch_trees/mini/birch_mini_tree_10");
addStructureID("trees/birch_trees/mini/birch_mini_tree_11");
addStructureID("trees/birch_trees/mini/birch_mini_tree_12");
addStructureID("trees/birch_trees/mini/birch_mini_tree_13");
addStructureID("trees/birch_trees/mini/birch_mini_tree_14");
addStructureID("trees/birch_trees/mini/birch_mini_tree_15");
addStructureID("trees/birch_trees/mini/birch_mini_tree_16");
addStructureID("trees/birch_trees/mini/birch_mini_tree_17");
addStructureID("trees/birch_trees/mini/birch_mini_tree_18");
addStructureID("trees/birch_trees/mini/birch_mini_tree_2");
addStructureID("trees/birch_trees/mini/birch_mini_tree_3");
addStructureID("trees/birch_trees/mini/birch_mini_tree_4");
addStructureID("trees/birch_trees/mini/birch_mini_tree_5");
addStructureID("trees/birch_trees/mini/birch_mini_tree_6");
addStructureID("trees/birch_trees/mini/birch_mini_tree_7");
addStructureID("trees/birch_trees/mini/birch_mini_tree_8");
addStructureID("trees/birch_trees/mini/birch_mini_tree_9");
//folder: trees\bonsai_trees\dark_oak
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_1");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_10");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_11");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_12");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_13");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_14");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_15");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_2");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_3");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_4");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_5");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_6");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_7");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_8");
addStructureID("trees/bonsai_trees/dark_oak/tree_bonsaidarkoak_9");
//folder: trees\bonsai_trees\oak
addStructureID("trees/bonsai_trees/oak/tree_bonsaidoak_5");
addStructureID("trees/bonsai_trees/oak/tree_bonsaioak_1");
addStructureID("trees/bonsai_trees/oak/tree_bonsaioak_2");
addStructureID("trees/bonsai_trees/oak/tree_bonsaioak_3");
addStructureID("trees/bonsai_trees/oak/tree_bonsaioak_4");
//folder: trees\darkoak_trees
addStructureID("trees/darkoak_trees/tree_darkoak_1");
addStructureID("trees/darkoak_trees/tree_darkoak_10");
addStructureID("trees/darkoak_trees/tree_darkoak_11");
addStructureID("trees/darkoak_trees/tree_darkoak_12");
addStructureID("trees/darkoak_trees/tree_darkoak_13");
addStructureID("trees/darkoak_trees/tree_darkoak_14");
addStructureID("trees/darkoak_trees/tree_darkoak_15");
addStructureID("trees/darkoak_trees/tree_darkoak_2");
addStructureID("trees/darkoak_trees/tree_darkoak_3");
addStructureID("trees/darkoak_trees/tree_darkoak_4");
addStructureID("trees/darkoak_trees/tree_darkoak_5");
addStructureID("trees/darkoak_trees/tree_darkoak_6");
addStructureID("trees/darkoak_trees/tree_darkoak_7");
addStructureID("trees/darkoak_trees/tree_darkoak_8");
addStructureID("trees/darkoak_trees/tree_darkoak_9");
//folder: trees\dead_swamp_trees
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_1");
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_2");
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_3");
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_4");
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_5");
addStructureID("trees/dead_swamp_trees/tree_dead_swamp_6");
//folder: trees\dead_trees\medium
addStructureID("trees/dead_trees/medium/dead_med_pinetree_1");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_10");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_2");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_3");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_4");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_5");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_6");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_7");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_8");
addStructureID("trees/dead_trees/medium/dead_med_pinetree_9");
//folder: trees\dead_trees\normal
addStructureID("trees/dead_trees/normal/tree_dead_1");
addStructureID("trees/dead_trees/normal/tree_dead_10");
addStructureID("trees/dead_trees/normal/tree_dead_11");
addStructureID("trees/dead_trees/normal/tree_dead_12");
addStructureID("trees/dead_trees/normal/tree_dead_13");
addStructureID("trees/dead_trees/normal/tree_dead_14");
addStructureID("trees/dead_trees/normal/tree_dead_2");
addStructureID("trees/dead_trees/normal/tree_dead_3");
addStructureID("trees/dead_trees/normal/tree_dead_4");
addStructureID("trees/dead_trees/normal/tree_dead_5");
addStructureID("trees/dead_trees/normal/tree_dead_6");
addStructureID("trees/dead_trees/normal/tree_dead_7");
addStructureID("trees/dead_trees/normal/tree_dead_8");
addStructureID("trees/dead_trees/normal/tree_dead_9");
//folder: trees\dead_trees
addStructureID("trees/dead_trees/sdeath_tree_13s");
//folder: trees\dry_trees
addStructureID("trees/dry_trees/dry_tree_1");
addStructureID("trees/dry_trees/dry_tree_10");
addStructureID("trees/dry_trees/dry_tree_11");
addStructureID("trees/dry_trees/dry_tree_12");
addStructureID("trees/dry_trees/dry_tree_13");
addStructureID("trees/dry_trees/dry_tree_14");
addStructureID("trees/dry_trees/dry_tree_15");
addStructureID("trees/dry_trees/dry_tree_16");
addStructureID("trees/dry_trees/dry_tree_2");
addStructureID("trees/dry_trees/dry_tree_3");
addStructureID("trees/dry_trees/dry_tree_4");
addStructureID("trees/dry_trees/dry_tree_5");
addStructureID("trees/dry_trees/dry_tree_6");
addStructureID("trees/dry_trees/dry_tree_7");
addStructureID("trees/dry_trees/dry_tree_8");
addStructureID("trees/dry_trees/dry_tree_9");
//folder: trees\fence_trees\birch
addStructureID("trees/fence_trees/birch/fence_birch_tree_1");
addStructureID("trees/fence_trees/birch/fence_birch_tree_10");
addStructureID("trees/fence_trees/birch/fence_birch_tree_11");
addStructureID("trees/fence_trees/birch/fence_birch_tree_12");
addStructureID("trees/fence_trees/birch/fence_birch_tree_13");
addStructureID("trees/fence_trees/birch/fence_birch_tree_14");
addStructureID("trees/fence_trees/birch/fence_birch_tree_15");
addStructureID("trees/fence_trees/birch/fence_birch_tree_2");
addStructureID("trees/fence_trees/birch/fence_birch_tree_3");
addStructureID("trees/fence_trees/birch/fence_birch_tree_4");
addStructureID("trees/fence_trees/birch/fence_birch_tree_5");
addStructureID("trees/fence_trees/birch/fence_birch_tree_6");
addStructureID("trees/fence_trees/birch/fence_birch_tree_7");
addStructureID("trees/fence_trees/birch/fence_birch_tree_8");
addStructureID("trees/fence_trees/birch/fence_birch_tree_9");
//folder: trees\fence_trees\normal
addStructureID("trees/fence_trees/normal/fence_tree");
addStructureID("trees/fence_trees/normal/fence_tree_1");
addStructureID("trees/fence_trees/normal/fence_tree_10");
addStructureID("trees/fence_trees/normal/fence_tree_11");
addStructureID("trees/fence_trees/normal/fence_tree_12");
addStructureID("trees/fence_trees/normal/fence_tree_13");
addStructureID("trees/fence_trees/normal/fence_tree_14");
addStructureID("trees/fence_trees/normal/fence_tree_15");
addStructureID("trees/fence_trees/normal/fence_tree_16");
addStructureID("trees/fence_trees/normal/fence_tree_17");
addStructureID("trees/fence_trees/normal/fence_tree_18");
addStructureID("trees/fence_trees/normal/fence_tree_19");
addStructureID("trees/fence_trees/normal/fence_tree_2");
addStructureID("trees/fence_trees/normal/fence_tree_20");
addStructureID("trees/fence_trees/normal/fence_tree_21");
addStructureID("trees/fence_trees/normal/fence_tree_22");
addStructureID("trees/fence_trees/normal/fence_tree_23");
addStructureID("trees/fence_trees/normal/fence_tree_24");
addStructureID("trees/fence_trees/normal/fence_tree_25");
addStructureID("trees/fence_trees/normal/fence_tree_26");
addStructureID("trees/fence_trees/normal/fence_tree_27");
addStructureID("trees/fence_trees/normal/fence_tree_28");
addStructureID("trees/fence_trees/normal/fence_tree_29");
addStructureID("trees/fence_trees/normal/fence_tree_3");
addStructureID("trees/fence_trees/normal/fence_tree_30");
addStructureID("trees/fence_trees/normal/fence_tree_31");
addStructureID("trees/fence_trees/normal/fence_tree_32");
addStructureID("trees/fence_trees/normal/fence_tree_33");
addStructureID("trees/fence_trees/normal/fence_tree_34");
addStructureID("trees/fence_trees/normal/fence_tree_35");
addStructureID("trees/fence_trees/normal/fence_tree_36");
addStructureID("trees/fence_trees/normal/fence_tree_37");
addStructureID("trees/fence_trees/normal/fence_tree_38");
addStructureID("trees/fence_trees/normal/fence_tree_4");
addStructureID("trees/fence_trees/normal/fence_tree_5");
addStructureID("trees/fence_trees/normal/fence_tree_6");
addStructureID("trees/fence_trees/normal/fence_tree_7");
addStructureID("trees/fence_trees/normal/fence_tree_8");
addStructureID("trees/fence_trees/normal/fence_tree_9");
addStructureID("trees/fence_trees/normal/fench_tree");
//folder: trees\ice_trees\big
addStructureID("trees/ice_trees/big/ice_treebig_1");
addStructureID("trees/ice_trees/big/ice_treebig_2");
addStructureID("trees/ice_trees/big/ice_treebig_3");
//folder: trees\ice_trees\normal
addStructureID("trees/ice_trees/normal/ice_tree_1");
addStructureID("trees/ice_trees/normal/ice_tree_10");
addStructureID("trees/ice_trees/normal/ice_tree_11");
addStructureID("trees/ice_trees/normal/ice_tree_12");
addStructureID("trees/ice_trees/normal/ice_tree_2");
addStructureID("trees/ice_trees/normal/ice_tree_3");
addStructureID("trees/ice_trees/normal/ice_tree_4");
addStructureID("trees/ice_trees/normal/ice_tree_5");
addStructureID("trees/ice_trees/normal/ice_tree_6");
addStructureID("trees/ice_trees/normal/ice_tree_7");
addStructureID("trees/ice_trees/normal/ice_tree_8");
addStructureID("trees/ice_trees/normal/ice_tree_9");
//folder: trees\oak_trees\big
addStructureID("trees/oak_trees/big/big_oak_tree_1");
addStructureID("trees/oak_trees/big/big_oak_tree_2");
addStructureID("trees/oak_trees/big/big_oak_tree_3");
addStructureID("trees/oak_trees/big/big_oak_tree_4");
//folder: trees\oak_trees\medium
addStructureID("trees/oak_trees/medium/oak_tree_med_1");
//folder: trees\oak_trees\mini
addStructureID("trees/oak_trees/mini/oak_mini_tree4");
addStructureID("trees/oak_trees/mini/oak_mini_tree_1");
addStructureID("trees/oak_trees/mini/oak_mini_tree_10");
addStructureID("trees/oak_trees/mini/oak_mini_tree_11");
addStructureID("trees/oak_trees/mini/oak_mini_tree_12");
addStructureID("trees/oak_trees/mini/oak_mini_tree_13");
addStructureID("trees/oak_trees/mini/oak_mini_tree_14");
addStructureID("trees/oak_trees/mini/oak_mini_tree_15");
addStructureID("trees/oak_trees/mini/oak_mini_tree_16");
addStructureID("trees/oak_trees/mini/oak_mini_tree_17");
addStructureID("trees/oak_trees/mini/oak_mini_tree_18");
addStructureID("trees/oak_trees/mini/oak_mini_tree_19");
addStructureID("trees/oak_trees/mini/oak_mini_tree_2");
addStructureID("trees/oak_trees/mini/oak_mini_tree_20");
addStructureID("trees/oak_trees/mini/oak_mini_tree_21");
addStructureID("trees/oak_trees/mini/oak_mini_tree_22");
addStructureID("trees/oak_trees/mini/oak_mini_tree_23");
addStructureID("trees/oak_trees/mini/oak_mini_tree_24");
addStructureID("trees/oak_trees/mini/oak_mini_tree_25");
addStructureID("trees/oak_trees/mini/oak_mini_tree_26");
addStructureID("trees/oak_trees/mini/oak_mini_tree_27");
addStructureID("trees/oak_trees/mini/oak_mini_tree_28");
addStructureID("trees/oak_trees/mini/oak_mini_tree_29");
addStructureID("trees/oak_trees/mini/oak_mini_tree_3");
addStructureID("trees/oak_trees/mini/oak_mini_tree_30");
addStructureID("trees/oak_trees/mini/oak_mini_tree_31");
addStructureID("trees/oak_trees/mini/oak_mini_tree_32");
addStructureID("trees/oak_trees/mini/oak_mini_tree_33");
addStructureID("trees/oak_trees/mini/oak_mini_tree_34");
addStructureID("trees/oak_trees/mini/oak_mini_tree_35");
addStructureID("trees/oak_trees/mini/oak_mini_tree_36");
addStructureID("trees/oak_trees/mini/oak_mini_tree_37");
addStructureID("trees/oak_trees/mini/oak_mini_tree_38");
addStructureID("trees/oak_trees/mini/oak_mini_tree_39");
addStructureID("trees/oak_trees/mini/oak_mini_tree_4");
addStructureID("trees/oak_trees/mini/oak_mini_tree_40");
addStructureID("trees/oak_trees/mini/oak_mini_tree_5");
addStructureID("trees/oak_trees/mini/oak_mini_tree_6");
addStructureID("trees/oak_trees/mini/oak_mini_tree_7");
addStructureID("trees/oak_trees/mini/oak_mini_tree_8");
addStructureID("trees/oak_trees/mini/oak_mini_tree_9");
//folder: trees\oak_trees\normal
addStructureID("trees/oak_trees/normal/oak_tree_1");
addStructureID("trees/oak_trees/normal/oak_tree_10");
addStructureID("trees/oak_trees/normal/oak_tree_11");
addStructureID("trees/oak_trees/normal/oak_tree_12");
addStructureID("trees/oak_trees/normal/oak_tree_13");
addStructureID("trees/oak_trees/normal/oak_tree_14");
addStructureID("trees/oak_trees/normal/oak_tree_15");
addStructureID("trees/oak_trees/normal/oak_tree_16");
addStructureID("trees/oak_trees/normal/oak_tree_17");
addStructureID("trees/oak_trees/normal/oak_tree_18");
addStructureID("trees/oak_trees/normal/oak_tree_19");
addStructureID("trees/oak_trees/normal/oak_tree_2");
addStructureID("trees/oak_trees/normal/oak_tree_20");
addStructureID("trees/oak_trees/normal/oak_tree_21");
addStructureID("trees/oak_trees/normal/oak_tree_22");
addStructureID("trees/oak_trees/normal/oak_tree_23");
addStructureID("trees/oak_trees/normal/oak_tree_3");
addStructureID("trees/oak_trees/normal/oak_tree_4");
addStructureID("trees/oak_trees/normal/oak_tree_5");
addStructureID("trees/oak_trees/normal/oak_tree_6");
addStructureID("trees/oak_trees/normal/oak_tree_7");
addStructureID("trees/oak_trees/normal/oak_tree_8");
addStructureID("trees/oak_trees/normal/oak_tree_9");
//folder: trees\palm_trees\big_palm
addStructureID("trees/palm_trees/big_palm/bigtree_palm_1");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_10");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_11");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_2");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_3");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_4");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_5");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_6");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_7");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_8");
addStructureID("trees/palm_trees/big_palm/bigtree_palm_9");
//folder: trees\palm_trees\normal_palm
addStructureID("trees/palm_trees/normal_palm/tree_palm_1");
addStructureID("trees/palm_trees/normal_palm/tree_palm_10");
addStructureID("trees/palm_trees/normal_palm/tree_palm_11");
addStructureID("trees/palm_trees/normal_palm/tree_palm_12");
addStructureID("trees/palm_trees/normal_palm/tree_palm_13");
addStructureID("trees/palm_trees/normal_palm/tree_palm_14");
addStructureID("trees/palm_trees/normal_palm/tree_palm_15");
addStructureID("trees/palm_trees/normal_palm/tree_palm_16");
addStructureID("trees/palm_trees/normal_palm/tree_palm_17");
addStructureID("trees/palm_trees/normal_palm/tree_palm_18");
addStructureID("trees/palm_trees/normal_palm/tree_palm_19");
addStructureID("trees/palm_trees/normal_palm/tree_palm_2");
addStructureID("trees/palm_trees/normal_palm/tree_palm_20");
addStructureID("trees/palm_trees/normal_palm/tree_palm_21");
addStructureID("trees/palm_trees/normal_palm/tree_palm_22");
addStructureID("trees/palm_trees/normal_palm/tree_palm_23");
addStructureID("trees/palm_trees/normal_palm/tree_palm_24");
addStructureID("trees/palm_trees/normal_palm/tree_palm_25");
addStructureID("trees/palm_trees/normal_palm/tree_palm_26");
addStructureID("trees/palm_trees/normal_palm/tree_palm_27");
addStructureID("trees/palm_trees/normal_palm/tree_palm_28");
addStructureID("trees/palm_trees/normal_palm/tree_palm_29");
addStructureID("trees/palm_trees/normal_palm/tree_palm_3");
addStructureID("trees/palm_trees/normal_palm/tree_palm_30");
addStructureID("trees/palm_trees/normal_palm/tree_palm_31");
addStructureID("trees/palm_trees/normal_palm/tree_palm_32");
addStructureID("trees/palm_trees/normal_palm/tree_palm_33");
addStructureID("trees/palm_trees/normal_palm/tree_palm_4");
addStructureID("trees/palm_trees/normal_palm/tree_palm_5");
addStructureID("trees/palm_trees/normal_palm/tree_palm_6");
addStructureID("trees/palm_trees/normal_palm/tree_palm_7");
addStructureID("trees/palm_trees/normal_palm/tree_palm_8");
addStructureID("trees/palm_trees/normal_palm/tree_palm_9");
//folder: trees\pine_broken_trees
addStructureID("trees/pine_broken_trees/pine_tree_broken_0");
addStructureID("trees/pine_broken_trees/pine_tree_broken_1");
addStructureID("trees/pine_broken_trees/pine_tree_broken_10");
addStructureID("trees/pine_broken_trees/pine_tree_broken_11");
addStructureID("trees/pine_broken_trees/pine_tree_broken_12");
addStructureID("trees/pine_broken_trees/pine_tree_broken_13");
addStructureID("trees/pine_broken_trees/pine_tree_broken_14");
addStructureID("trees/pine_broken_trees/pine_tree_broken_15");
addStructureID("trees/pine_broken_trees/pine_tree_broken_16");
addStructureID("trees/pine_broken_trees/pine_tree_broken_17");
addStructureID("trees/pine_broken_trees/pine_tree_broken_18");
addStructureID("trees/pine_broken_trees/pine_tree_broken_2");
addStructureID("trees/pine_broken_trees/pine_tree_broken_3");
addStructureID("trees/pine_broken_trees/pine_tree_broken_4");
addStructureID("trees/pine_broken_trees/pine_tree_broken_5");
addStructureID("trees/pine_broken_trees/pine_tree_broken_6");
addStructureID("trees/pine_broken_trees/pine_tree_broken_7");
addStructureID("trees/pine_broken_trees/pine_tree_broken_8");
addStructureID("trees/pine_broken_trees/pine_tree_broken_9");
//folder: trees\pine_trees\big
addStructureID("trees/pine_trees/big/big_pine_tree5");
addStructureID("trees/pine_trees/big/big_pine_tree_1");
addStructureID("trees/pine_trees/big/big_pine_tree_2");
addStructureID("trees/pine_trees/big/big_pine_tree_3");
addStructureID("trees/pine_trees/big/big_pine_tree_4");
addStructureID("trees/pine_trees/big/big_pine_tree_5");
addStructureID("trees/pine_trees/big/big_pine_tree_6");
//folder: trees\pine_trees\medium
addStructureID("trees/pine_trees/medium/pine_tree_med_1");
addStructureID("trees/pine_trees/medium/pine_tree_med_10");
addStructureID("trees/pine_trees/medium/pine_tree_med_11");
addStructureID("trees/pine_trees/medium/pine_tree_med_12");
addStructureID("trees/pine_trees/medium/pine_tree_med_13");
addStructureID("trees/pine_trees/medium/pine_tree_med_14");
addStructureID("trees/pine_trees/medium/pine_tree_med_15");
addStructureID("trees/pine_trees/medium/pine_tree_med_16");
addStructureID("trees/pine_trees/medium/pine_tree_med_17");
addStructureID("trees/pine_trees/medium/pine_tree_med_18");
addStructureID("trees/pine_trees/medium/pine_tree_med_19");
addStructureID("trees/pine_trees/medium/pine_tree_med_2");
addStructureID("trees/pine_trees/medium/pine_tree_med_20");
addStructureID("trees/pine_trees/medium/pine_tree_med_3");
addStructureID("trees/pine_trees/medium/pine_tree_med_4");
addStructureID("trees/pine_trees/medium/pine_tree_med_5");
addStructureID("trees/pine_trees/medium/pine_tree_med_6");
addStructureID("trees/pine_trees/medium/pine_tree_med_7");
addStructureID("trees/pine_trees/medium/pine_tree_med_8");
addStructureID("trees/pine_trees/medium/pine_tree_med_9");
//folder: trees\pine_trees\normal
addStructureID("trees/pine_trees/normal/pine_tree_41");
addStructureID("trees/pine_trees/normal/pine_tree_42");
addStructureID("trees/pine_trees/normal/pine_tree_43");
addStructureID("trees/pine_trees/normal/pine_tree_44");
addStructureID("trees/pine_trees/normal/pine_tree_445");
addStructureID("trees/pine_trees/normal/pine_tree_45");
addStructureID("trees/pine_trees/normal/pine_tree_46");
addStructureID("trees/pine_trees/normal/pine_tree_47");
addStructureID("trees/pine_trees/normal/pine_tree_48");
addStructureID("trees/pine_trees/normal/pine_tree_49");
addStructureID("trees/pine_trees/normal/pine_tree_50");
addStructureID("trees/pine_trees/normal/pine_tree_51");
addStructureID("trees/pine_trees/normal/pine_tree_52");
addStructureID("trees/pine_trees/normal/pine_tree_53");
addStructureID("trees/pine_trees/normal/pine_tree_54");
addStructureID("trees/pine_trees/normal/tree_pine_1");
addStructureID("trees/pine_trees/normal/tree_pine_10");
addStructureID("trees/pine_trees/normal/tree_pine_11");
addStructureID("trees/pine_trees/normal/tree_pine_12");
addStructureID("trees/pine_trees/normal/tree_pine_13");
addStructureID("trees/pine_trees/normal/tree_pine_14");
addStructureID("trees/pine_trees/normal/tree_pine_15");
addStructureID("trees/pine_trees/normal/tree_pine_16");
addStructureID("trees/pine_trees/normal/tree_pine_17");
addStructureID("trees/pine_trees/normal/tree_pine_18");
addStructureID("trees/pine_trees/normal/tree_pine_19");
addStructureID("trees/pine_trees/normal/tree_pine_2");
addStructureID("trees/pine_trees/normal/tree_pine_20");
addStructureID("trees/pine_trees/normal/tree_pine_21");
addStructureID("trees/pine_trees/normal/tree_pine_22");
addStructureID("trees/pine_trees/normal/tree_pine_23");
addStructureID("trees/pine_trees/normal/tree_pine_24");
addStructureID("trees/pine_trees/normal/tree_pine_25");
addStructureID("trees/pine_trees/normal/tree_pine_26");
addStructureID("trees/pine_trees/normal/tree_pine_27");
addStructureID("trees/pine_trees/normal/tree_pine_28");
addStructureID("trees/pine_trees/normal/tree_pine_29");
addStructureID("trees/pine_trees/normal/tree_pine_3");
addStructureID("trees/pine_trees/normal/tree_pine_30");
addStructureID("trees/pine_trees/normal/tree_pine_31");
addStructureID("trees/pine_trees/normal/tree_pine_32");
addStructureID("trees/pine_trees/normal/tree_pine_33");
addStructureID("trees/pine_trees/normal/tree_pine_34");
addStructureID("trees/pine_trees/normal/tree_pine_35");
addStructureID("trees/pine_trees/normal/tree_pine_36");
addStructureID("trees/pine_trees/normal/tree_pine_37");
addStructureID("trees/pine_trees/normal/tree_pine_38");
addStructureID("trees/pine_trees/normal/tree_pine_39");
addStructureID("trees/pine_trees/normal/tree_pine_4");
addStructureID("trees/pine_trees/normal/tree_pine_40");
addStructureID("trees/pine_trees/normal/tree_pine_5");
addStructureID("trees/pine_trees/normal/tree_pine_6");
addStructureID("trees/pine_trees/normal/tree_pine_7");
addStructureID("trees/pine_trees/normal/tree_pine_8");
addStructureID("trees/pine_trees/normal/tree_pine_9");
//folder: trees\psychic_trees\long_psychic_trees
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_1");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_10");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_2");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_3");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_4");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_5");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_6");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_7");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_8");
addStructureID("trees/psychic_trees/long_psychic_trees/longtree_psychic_9");
//folder: trees\psychic_trees\normal_psychic_trees\1
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_1");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_10");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_2");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_3");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_4");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_5");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_6");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_7");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_8");
addStructureID("trees/psychic_trees/normal_psychic_trees/1/tree_psychic_9");
//folder: trees\psychic_trees\normal_psychic_trees\2
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_1");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_10");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_2");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_3");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_4");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_5");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_6");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_7");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_8");
addStructureID("trees/psychic_trees/normal_psychic_trees/2/tree2_psychic_9");
//folder: trees\snow_darkoak_trees
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_1");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_10");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_11");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_12");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_13");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_2");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_3");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_4");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_5");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_6");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_7");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_8");
addStructureID("trees/snow_darkoak_trees/tree_snowdarkoak_9");
//folder: trees\snow_pine_trees\medium
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_1");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_10");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_2");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_3");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_4");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_5");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_6");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_7");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_8");
addStructureID("trees/snow_pine_trees/medium/pine_tree_med_snow_9");
//folder: trees\swamp_trees\big
addStructureID("trees/swamp_trees/big/big_swamp_tree_1");
//folder: trees\swamp_trees
addStructureID("trees/swamp_trees/swamp_tree_1");
addStructureID("trees/swamp_trees/swamp_tree_10");
addStructureID("trees/swamp_trees/swamp_tree_11");
addStructureID("trees/swamp_trees/swamp_tree_12");
addStructureID("trees/swamp_trees/swamp_tree_2");
addStructureID("trees/swamp_trees/swamp_tree_3");
addStructureID("trees/swamp_trees/swamp_tree_4");
addStructureID("trees/swamp_trees/swamp_tree_5");
addStructureID("trees/swamp_trees/swamp_tree_6");
addStructureID("trees/swamp_trees/swamp_tree_7");
addStructureID("trees/swamp_trees/swamp_tree_8");
addStructureID("trees/swamp_trees/swamp_tree_9");
//folder: trees\swamp_water_trees
addStructureID("trees/swamp_water_trees/swamp_water_tree_1");
addStructureID("trees/swamp_water_trees/swamp_water_tree_2");
addStructureID("trees/swamp_water_trees/swamp_water_tree_3");
addStructureID("trees/swamp_water_trees/swamp_water_tree_4");
addStructureID("trees/swamp_water_trees/swamp_water_tree_5");
addStructureID("trees/swamp_water_trees/swamp_water_tree_6");
//folder: trees\water_trees
addStructureID("trees/water_trees/water_tree_1");
addStructureID("trees/water_trees/water_tree_10");
addStructureID("trees/water_trees/water_tree_11");
addStructureID("trees/water_trees/water_tree_12");
addStructureID("trees/water_trees/water_tree_13");
addStructureID("trees/water_trees/water_tree_14");
addStructureID("trees/water_trees/water_tree_15");
addStructureID("trees/water_trees/water_tree_16");
addStructureID("trees/water_trees/water_tree_17");
addStructureID("trees/water_trees/water_tree_18");
addStructureID("trees/water_trees/water_tree_19");
addStructureID("trees/water_trees/water_tree_2");
addStructureID("trees/water_trees/water_tree_3");
addStructureID("trees/water_trees/water_tree_4");
addStructureID("trees/water_trees/water_tree_5");
addStructureID("trees/water_trees/water_tree_6");
addStructureID("trees/water_trees/water_tree_7");
addStructureID("trees/water_trees/water_tree_8");
addStructureID("trees/water_trees/water_tree_9");
    }

    private void addStructureID(String id){
        structures.add(id);
    }
}
